name: CI build

on: [push, pull_request]

jobs:
  gcc-10-debug:
    name: x86 gcc-10 Debug
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ctest build
      uses: gatzka/ctest-build-action@v1.6.0
      with:
        install_deps: ./.github/workflows/install-deps.sh
        ctest_toolchain_file: /tmp/fast_copy/toolchains/x86-linux-gcc-10.cmake
        ctest_configuration_type: Debug

